import {useI18n} from '../i18n/index.tsx';
import {heatColor} from '../mapMath.ts';
import type {Cost,Telemetry} from '../types.ts';
export function EnergyPanel({data,selected,onSelect}:{data:Telemetry|null;selected:Cost|null;onSelect:(e:Cost)=>void}) {
 const {t,n}=useI18n(),costs=data?.knowledge||[],measured=costs.filter(e=>e.move_samples>0);
 const min=Math.min(...measured.map(e=>e.energy_per_m)),max=Math.max(...measured.map(e=>e.energy_per_m));
 const detail=selected&&costs.find(e=>e.cell.x===selected.cell.x&&e.cell.y===selected.cell.y);
 const diag=data?.energy_diagnostics;
 return <section className="panel energy-panel"><div className="panel-head"><h2>{t('energy.title')}</h2><span>{t('energy.unit')}</span></div><div className="energy-body"><div><p className="section-note">{t(data?.session.mode==='adaptive'?'mode.adaptiveHint':'mode.baselineHint')}</p>{measured.length?<div className="heat-scale"><label>{t('energy.scale')}</label><div className="heat-gradient" style={min===max?{background:heatColor(min,min,max)}:undefined}/><div className="scale-labels">{[min,(min+max)/2,max].map((v,i)=><span key={i}>{n(v,2)}</span>)}</div></div>:<p className="muted">{t('energy.empty')}</p>}<p className="section-note">{t('energy.note')}</p><div className="diagnostics"><span>{diag?t('energy.accepted',{count:n(diag.accepted,0)}):t('metric.noData')}</span>{diag&&<span>{t('energy.rejected',{count:n(Object.values(diag.rejected).reduce((a,b)=>a+b,0),0)})}</span>}</div></div>
 <div className="energy-inspector"><label htmlFor="energy-cell">{t('energy.inspect')}</label><select id="energy-cell" value={detail?`${detail.cell.x}:${detail.cell.y}`:''} onChange={event=>{const e=costs.find(e=>`${e.cell.x}:${e.cell.y}`===event.target.value);if(e)onSelect(e)}}><option value="">{costs.length?t('energy.inspect'):t('energy.none')}</option>{costs.map(e=><option key={`${e.cell.x}:${e.cell.y}`} value={`${e.cell.x}:${e.cell.y}`}>{t('energy.cell',{x:n(e.cell.x,2),y:n(e.cell.y,2)})}</option>)}</select>
 {detail&&<div className="cost-detail"><strong><i style={{background:detail.move_samples?heatColor(detail.energy_per_m,min,max):'#8897aa'}}/>{t(detail.move_samples?'energy.measured':'energy.prior')}</strong><p>{n(detail.energy_per_m,2)} {t('energy.unit')}</p><span>{t('energy.samples',{count:n(detail.move_samples||0,0)})}</span><span>{detail.uncertainty==null?t('energy.unknown'):t('energy.uncertainty',{value:n(detail.uncertainty,3)})}</span><p>{detail.energy_per_rad==null?t('metric.noData'):`${n(detail.energy_per_rad,3)} ${t('energy.turnUnit')}`}</p><span>{t('energy.turnSamples',{count:n(detail.turn_samples||0,0)})}</span><span>{detail.turn_uncertainty==null?t('energy.unknown'):t('energy.uncertainty',{value:n(detail.turn_uncertainty,3)})}</span></div>}</div></div></section>;
}
