import {useEffect,useRef,useState} from 'react';
import type {Cost,Grid,Point,Telemetry} from '../types.ts';
import {BASE,costAt,fitMap,heatColor,occupancyColor,rasterOffset,scaleLength,screenPath,screenToWorld,worldToScreen,type View} from '../mapMath.ts';
import {palette,FIXED_ENERGY_MAX} from '../palette.ts';
import {Icon} from './Icon.tsx';
import {useI18n} from '../i18n/index.tsx';
export function WorldMap({data,grid,online,presentation,onInspect,relative}:{data:Telemetry|null;grid:Grid|null;online:boolean;presentation:boolean;onInspect:(cost:Cost)=>void;relative:boolean}) {
 const {t,n}=useI18n();
 const canvas=useRef<HTMLCanvasElement>(null),raster=useRef<HTMLCanvasElement|null>(null);
 const [size,setSize]=useState({w:800,h:560});
 const [view,setView]=useState<View>({x:-2,y:-.5,zoom:80}),[follow,setFollow]=useState(false),[pointer,setPointer]=useState<Point|null>(null);
 const [interactive,setInteractive]=useState(false);
 const active=!!data&&['running','paused','returning'].includes(data.state.status);
 const [layers,setLayers]=useState({path:true,visited:true,costs:true});
 const drag=useRef<{x:number;y:number;view:View}|null>(null), fitted=useRef<number|null>(null),automaticFit=useRef(true);
 const currentView=follow&&data?.robot_pose?{...view,...data.robot_pose}:view;
 useEffect(()=>{const c=canvas.current;if(!c)return;const observer=new ResizeObserver(()=>{const r=c.getBoundingClientRect();setSize({w:r.width,h:r.height})});observer.observe(c);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!grid){raster.current=null;fitted.current=null;automaticFit.current=true;return}const c=document.createElement('canvas');c.width=grid.width;c.height=grid.height;const ctx=c.getContext('2d');if(!ctx)return;const image=ctx.createImageData(c.width,c.height);
 grid.data.forEach((value,i)=>{const j=rasterOffset(i,grid.width,grid.height);image.data.set([...occupancyColor(value),255],j)});ctx.putImageData(image,0,0);raster.current=c;
 },[grid]);
 useEffect(()=>{if(grid&&(fitted.current!==grid.revision||automaticFit.current)){setView(fitMap(grid,size.w,size.h));fitted.current=grid.revision}},[grid,size]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;
 const {w,h}=size,dpr=window.devicePixelRatio||1;
 c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);
 const v=currentView,z=v.zoom,px=(p:Point)=>worldToScreen(p,v,w,h);
 ctx.fillStyle=palette.map;ctx.fillRect(0,0,w,h);ctx.strokeStyle=palette.grid;ctx.lineWidth=.6;
 const step=z<30?5:1;
 for(let x=Math.floor((v.x-w/2/z)/step)*step;x<v.x+w/2/z;x+=step){const q=px({x,y:0});ctx.beginPath();ctx.moveTo(q.x,0);ctx.lineTo(q.x,h);ctx.stroke()}
 for(let y=Math.floor((v.y-h/2/z)/step)*step;y<v.y+h/2/z;y+=step){const q=px({x:0,y});ctx.beginPath();ctx.moveTo(0,q.y);ctx.lineTo(w,q.y);ctx.stroke()}
 if(grid&&raster.current){const o=px(grid.origin);ctx.save();ctx.translate(o.x,o.y);ctx.rotate(-grid.origin_yaw);ctx.imageSmoothingEnabled=false;ctx.drawImage(raster.current,0,-grid.height*grid.resolution*z,grid.width*grid.resolution*z,grid.height*grid.resolution*z);ctx.restore()}
 const measured=(data?.knowledge||[]).filter(e=>e.move_samples>0),min=relative?Math.min(...measured.map(e=>e.energy_per_m)):0,max=relative?Math.max(...measured.map(e=>e.energy_per_m)):FIXED_ENERGY_MAX;
 if(layers.costs)(data?.knowledge||[]).forEach(e=>{const p=px(e.cell),cell=.5*z;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(-(grid?.origin_yaw??0));ctx.fillStyle=e.move_samples?heatColor(e.energy_per_m,min,max):palette.prior;ctx.globalAlpha=e.move_samples?.48:.08;ctx.fillRect(-cell/2,-cell/2,cell,cell);ctx.globalAlpha=.7;ctx.strokeStyle=e.move_samples?heatColor(e.energy_per_m,min,max):palette.prior;ctx.setLineDash(e.move_samples?[]:[2,3]);ctx.strokeRect(-cell/2,-cell/2,cell,cell);ctx.restore()});
 const line=(points:Point[],color:string,width:number,dash:number[])=>{const path=screenPath(points,v,w,h);if(!path.length)return;ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([])};
 if(layers.visited)line(data?.trajectory||[],palette.trajectory,presentation?4:2.5,[]);
 if(layers.path){line(data?.planned_path||[],palette.ink,presentation?7:5,[]);line(data?.planned_path||[],palette.accent,presentation?3:2,[7,6])}
 const home=px(BASE);ctx.fillStyle=palette.map;ctx.strokeStyle=palette.base;ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(home.x-13,home.y-13,26,26,5);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(home.x-7,home.y);ctx.lineTo(home.x,home.y-6);ctx.lineTo(home.x+7,home.y);ctx.moveTo(home.x-5,home.y-2);ctx.lineTo(home.x-5,home.y+6);ctx.lineTo(home.x+5,home.y+6);ctx.lineTo(home.x+5,home.y-2);ctx.stroke();ctx.fillStyle=palette.base;ctx.font='13px sans-serif';ctx.textAlign='left';ctx.fillText(t('map.base'),home.x+20,home.y+4);
 (data?.collected_positions||[]).forEach(p=>{const q=px(p);ctx.fillStyle=palette.robot;ctx.strokeStyle=palette.robotInk;ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,6,0,Math.PI*2);ctx.fill();ctx.stroke()});
 const goal=active?data?.state.goal?.target:null;if(goal){const q=px(goal);ctx.strokeStyle=palette.accent;ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,10,0,Math.PI*2);ctx.moveTo(q.x-16,q.y);ctx.lineTo(q.x+16,q.y);ctx.moveTo(q.x,q.y-16);ctx.lineTo(q.x,q.y+16);ctx.stroke()}
 if(data?.robot_pose){const p=px(data.robot_pose),s=presentation?1.4:1;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(-data.robot_yaw);ctx.scale(s,s);
 ctx.fillStyle=online?palette.robot:palette.muted;ctx.strokeStyle=palette.robotInk;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,11,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=palette.robotInk;ctx.fillRect(-7,-13,10,4);ctx.fillRect(-7,9,10,4);ctx.beginPath();ctx.arc(-3,0,4,0,Math.PI*2);ctx.fill();ctx.fillStyle=online?palette.text:palette.muted;ctx.beginPath();ctx.moveTo(25,0);ctx.lineTo(14,-5);ctx.lineTo(14,5);ctx.closePath();ctx.fill();ctx.restore();}
 const scale=scaleLength(z),length=scale*z;ctx.strokeStyle=palette.text;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(w-24-length,h-25);ctx.lineTo(w-24,h-25);ctx.stroke();ctx.font='11px sans-serif';ctx.textAlign='right';ctx.fillStyle=palette.muted;ctx.fillText(t('map.scale',{value:n(scale,scale<1?2:0)}),w-24,h-36);
 },[data,grid,size,currentView.x,currentView.y,currentView.zoom,layers,online,presentation,t,n,relative,active]);
 const reset=()=>{automaticFit.current=true;setFollow(false);setView(fitMap(grid,size.w,size.h))};
 const zoom=(factor:number,anchor?:Point)=>{automaticFit.current=false;const v=currentView,next={...v,zoom:Math.max(8,Math.min(600,v.zoom*factor))};if(anchor){const before=screenToWorld(anchor,v,size.w,size.h),after=screenToWorld(anchor,next,size.w,size.h);next.x+=before.x-after.x;next.y+=before.y-after.y;setFollow(false)}setView(next)};
 const readings=(data?.knowledge||[]).filter(e=>e.move_samples>0);
 const range={min:relative?Math.min(...readings.map(e=>e.energy_per_m)):0,max:relative?Math.max(...readings.map(e=>e.energy_per_m)):FIXED_ENERGY_MAX};
 const hovered=pointer&&layers.costs?costAt(pointer,data?.knowledge||[],grid?.origin_yaw??0):undefined;
 return <div className={`map-area ${interactive?'interactive':'reading'}`}><canvas ref={canvas} tabIndex={0} aria-label={t('map.canvas')} onKeyDown={e=>{const delta=40/currentView.zoom;const offsets:Record<string,Point>={ArrowLeft:{x:-delta,y:0},ArrowRight:{x:delta,y:0},ArrowUp:{x:0,y:delta},ArrowDown:{x:0,y:-delta}};if(offsets[e.key]){e.preventDefault();automaticFit.current=false;setFollow(false);setView({...currentView,x:currentView.x+offsets[e.key].x,y:currentView.y+offsets[e.key].y})}else if(e.key==='+'||e.key==='='){e.preventDefault();zoom(1.2)}else if(e.key==='-'){e.preventDefault();zoom(1/1.2)}else if(e.key==='Home'){e.preventDefault();reset()}}} onWheel={e=>{if(!interactive&&!e.ctrlKey)return;e.preventDefault();const r=e.currentTarget.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.001),{x:e.clientX-r.left,y:e.clientY-r.top})}} onPointerDown={e=>{if(e.pointerType==='touch'&&!interactive)return;automaticFit.current=false;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,view:currentView};setView(currentView);setFollow(false)}} onPointerUp={e=>{const d=drag.current;drag.current=null;if(d&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<5&&hovered)onInspect(hovered);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}} onLostPointerCapture={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}} onPointerLeave={()=>setPointer(null)} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setPointer(screenToWorld({x:e.clientX-r.left,y:e.clientY-r.top},currentView,size.w,size.h));const d=drag.current;if(d)setView({...d.view,x:d.view.x-(e.clientX-d.x)/d.view.zoom,y:d.view.y+(e.clientY-d.y)/d.view.zoom})}}/>
 <div className="map-tools"><button title={t('map.zoomIn')} aria-label={t('map.zoomIn')} onClick={()=>zoom(1.2)}><Icon name="plus"/></button><button title={t('map.zoomOut')} aria-label={t('map.zoomOut')} onClick={()=>zoom(1/1.2)}><Icon name="minus"/></button><button aria-label={t('map.reset')} title={t('map.reset')} onClick={reset}><Icon name="fit"/></button><button aria-label={t('map.follow')} title={t('map.follow')} aria-pressed={follow} className={follow?'selected':''} onClick={()=>{automaticFit.current=false;setView(currentView);setFollow(!follow)}}><Icon name="follow"/></button><button title={t('console.mapPan')} aria-label={t('console.mapPan')} aria-pressed={interactive} className={interactive?'selected':''} onClick={()=>{drag.current=null;setInteractive(v=>!v)}}><Icon name="pan"/><span>{t('console.mapPan')}</span></button></div>
 <details className="map-layers"><summary>{t('console.layers')}</summary><div>{(['path','visited','costs'] as const).map(k=><label key={k}><input type="checkbox" checked={layers[k]} onChange={()=>setLayers(v=>({...v,[k]:!v[k]}))}/>{t(`map.${k}`)}</label>)}</div></details>
 <div className="map-frame">{t('map.frame')}</div>
 {layers.costs&&readings.length>0&&<div className="map-heat-scale" aria-label={t('console.energyScale')} title={t(relative?'console.energyRelativeHint':'console.energyReference')}><small>{t('energy.unit')}</small><span>{t(relative?'console.energyRelative':'console.energyFixed')}</span><div className="heat-gradient" style={range.min===range.max?{background:heatColor(range.min,range.min,range.max)}:undefined}/><div className="scale-labels"><span>{n(range.min,2)}</span><span>{n(range.max,2)}</span></div></div>}
 {hovered&&<div className="map-tooltip" role="status"><strong>{t(hovered.move_samples?'energy.measured':'energy.prior')}</strong><span>{n(hovered.energy_per_m,2)} {t('energy.unit')}</span><span>{t('energy.samples',{count:n(hovered.move_samples||0,0)})}</span><span>{hovered.uncertainty==null?t('energy.unknown'):t('energy.uncertainty',{value:n(hovered.uncertainty,3)})}</span></div>}
 <div className="map-bottom"><div className="legend">{(['robot','path','visited'] as const).map(k=><span key={k}><i className={`legend-mark ${k}`}/>{t(`map.${k}`)}</span>)}<details><summary>{t('console.legend')}</summary><div>{(['base','samples','wall','free','unknown'] as const).map(k=><span key={k}><i className={`legend-mark ${k}`}/>{t(`map.${k}`)}</span>)}{layers.costs&&<><span><i className="legend-mark measured"/>{t('energy.measured')}</span><span><i className="legend-mark prior"/>{t('energy.prior')}</span></>}</div></details></div><div className="cursor">{pointer?t('map.position',{x:n(pointer.x,2),y:n(pointer.y,2)}):t(interactive?'console.panHint':'console.readHint')}</div></div>
 {!online&&<div className="map-offline"><strong>{data?t('map.stale'):t('map.wait')}</strong><small>{t('map.noMotion')}</small></div>}
 </div>;
}
