"""Подписи будущих реализаций. Protocol не выполняет работу."""
from typing import Protocol
from .types import (
    Command, CostEstimate, EnergyMeasurement, MissionState,
    Observation, Point, Result, StartRequest, Subgoal,
)


class Planner(Protocol):
    async def propose(self, observation: Observation, feedback: str = "") -> Subgoal: ...


class EnergyModel(Protocol):
    def update(self, measurement: EnergyMeasurement) -> None: ...
    def estimate(self, point: Point) -> CostEstimate: ...


class Navigator(Protocol):
    def plan(self, start: Point, target: Point) -> list[Point]: ...
    async def follow(self, path: list[Point]) -> Result: ...
    async def stop(self) -> None: ...


class TaskServices(Protocol):
    async def collect(self) -> Result: ...
    async def finish(self) -> Result: ...


class MissionControl(Protocol):
    async def start(self, request: StartRequest) -> MissionState: ...
    async def command(self, command: Command) -> MissionState: ...
    def state(self) -> MissionState: ...
