"""Подписи будущих реализаций. Protocol не выполняет работу."""
from typing import Protocol
from .types import (
    Command, CostEstimate, EnergyMeasurement, MissionState,
    Observation, Point, Result, StartRequest, Subgoal,
    TurnCostEstimate, TurnEnergyMeasurement,
)


class Planner(Protocol):
    async def propose(self, observation: Observation, feedback: str = "") -> Subgoal: ...


class EnergyModel(Protocol):
    def update(self, measurement: EnergyMeasurement) -> None: ...
    def estimate(self, point: Point) -> CostEstimate: ...
    def update_turn(self, measurement: TurnEnergyMeasurement) -> None: ...
    def estimate_turn(self, point: Point) -> TurnCostEstimate: ...
    # One action: distance_m>0 OR angle_rad>0; the inactive value is zero.
    def estimate_energy(self, point: Point, distance_m: float, angle_rad: float) -> float | None: ...


class TurnEnergyModel(Protocol):
    def update(self, measurement: TurnEnergyMeasurement) -> None: ...
    def estimate(self, point: Point) -> TurnCostEstimate: ...


class Navigator(Protocol):
    def plan(self, start: Point, target: Point) -> list[Point]: ...
    async def follow(self, path: list[Point]) -> Result: ...
    async def stop(self) -> None: ...


class TaskServices(Protocol):
    async def collect(self) -> Result: ...
    async def finish(self) -> Result: ...


class MissionControl(Protocol):
    async def start(self, request: StartRequest) -> MissionState: ...
    async def command(self, command: Command) -> MissionState: ...
    def state(self) -> MissionState: ...
