import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {I18nProvider,useI18n} from './i18n/index.tsx';
import {WorldMap} from './components/WorldMap.tsx';
import {EnergyPanel} from './components/EnergyPanel.tsx';
import {Journal} from './components/Journal.tsx';
import {actionText,decisionSource,reasonText,statusText} from './presentation.ts';
import type {Cost,Grid,Session,Telemetry} from './types.ts';
import type {Key} from './i18n/core.ts';
import {sendCommand,type Command,type Notice} from './api.ts';
import './style.css';
const INITIAL:Session={scenario:'easy',seed:1,mode:'baseline',planner_mode:'algorithmic'};
const commandKeys:Record<string,Key>={start:'mission.start',pause:'mission.pause',resume:'mission.resume',return:'mission.return',stop:'mission.stop',reset:'mission.reset'};
function App(){
 const {t,n,locale,setLocale}=useI18n();
 const [data,setData]=useState<Telemetry|null>(null),[grid,setGrid]=useState<Grid|null>(null),[session,setSession]=useState(INITIAL);
 const [mapAttempt,setMapAttempt]=useState(0);
 const [socket,setSocket]=useState('connecting'),[busy,setBusy]=useState(false),[mapError,setMapError]=useState(false);
 const [notice,setNotice]=useState<Notice|null>(null);
 const [presentation,setPresentation]=useState(false),[cost,setCost]=useState<Cost|null>(null);
 const received=useRef(0),inFlight=useRef(false),resetDialog=useRef<HTMLDialogElement>(null);
 const [resetPending,setResetPending]=useState(false);
 useEffect(()=>{const dialog=resetDialog.current;if(resetPending)dialog?.showModal();else dialog?.close()},[resetPending]);
 useEffect(()=>{let ws:WebSocket,timer:ReturnType<typeof setTimeout>,alive=true;
 function connect(){if(!alive)return;setSocket('connecting');ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/telemetry`);
 ws.onmessage=e=>{try{const value=JSON.parse(e.data) as Telemetry;if(!value.state||!value.session||!Array.isArray(value.journal)||!Array.isArray(value.knowledge))throw Error('Invalid telemetry');received.current=Date.now();setData(value);setSocket('online')}catch{setSocket('error')}};
 ws.onerror=()=>{if(alive)setSocket('error')};ws.onclose=()=>{if(alive){setSocket('offline');timer=setTimeout(connect,2000)}}}
 connect();const stale=setInterval(()=>{if(received.current&&Date.now()-received.current>2000)setSocket('offline')},500);
 return()=>{alive=false;clearTimeout(timer);clearInterval(stale);ws?.close()};},[]);
 useEffect(()=>{const controller=new AbortController();setGrid(null);setMapError(false);if(!data?.map_revision)return;
 fetch('/api/map',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Map unavailable');return r.json()}).then((value:Grid)=>{if(!value.width||!value.height||!value.resolution||!Array.isArray(value.data)||value.data.length!==value.width*value.height)throw Error('Invalid map');setGrid(value)}).catch(()=>{if(!controller.signal.aborted)setMapError(true)});return()=>controller.abort();},[data?.map_revision,data?.session.seed,data?.session.scenario,mapAttempt]);
 useEffect(()=>{if(!presentation)return;const handler=(event:KeyboardEvent)=>{if(event.key==='Escape')setPresentation(false)};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[presentation]);
 const connection=socket==='online'?(data?.connection||'connecting'):socket,online=connection==='online';
 const status=data?.state.status||'idle',active=['running','paused','returning'].includes(status),obs=data?.state.observation;
 const selected=active&&data?data.session:session,total=({easy:3,medium:5,hard:7} as Record<string,number>)[data?.session.scenario||session.scenario]??0;
 async function action(cmd:Command,confirmed=false){
  if(inFlight.current)return;
  if(cmd==='reset'&&!confirmed){setResetPending(true);return}
  inFlight.current=true;setBusy(true);setNotice(null);
  try{
   const result=await sendCommand(cmd,session);
   if(result.kind==='reset'){setData(null);setGrid(null);setCost(null);received.current=0}
   setNotice(result);
  }finally{inFlight.current=false;setBusy(false)}
 }
 const source=decisionSource(data,t),reason=reasonText(data?.state.goal?.reason,t);
 const objective=['idle','finished','failed','stopped'].includes(status)?(status==='idle'?t('agent.wait'):statusText(status,t)):actionText(data?.state.goal?.action,t);
 const noticeText=busy?t('mission.wait'):notice?.kind==='accepted'?t('mission.accepted',{command:t(commandKeys[notice.command||'start'] as 'mission.start')}):notice?.kind==='reset'?t('mission.resetDone'):notice?.kind==='seed'?t('mission.seedError'):notice?.kind==='network'?t('mission.networkError'):notice?.kind==='response'?t('mission.responseError'):notice?.kind==='api'?t('mission.requestError',{code:n(notice.code||0,0)}):t('mission.watchdog');
 const safetyEvent=data?.events?.filter(e=>['hazard_hit','collision'].includes(e.type)).at(-1);
 const failure=data?.error||[...(data?.journal||[])].reverse().find(e=>e.text.startsWith('Failure:'))?.text;
 const lastEvent=data?.events?.at(-1),eventKeys:Record<string,Key>={sample_collected:'event.sample_collected',false_collect:'event.false_collect',hazard_hit:'event.hazard_hit',collision:'event.collision'};
 return <main className={presentation?'presentation':''}><header><a className="brand" href="#mission-map"><div className="brandmark">D<span>↗</span></div><div><strong>DID LAB</strong><p>{t('app.subtitle')}</p></div></a><div className="header-actions"><div className={`connection ${connection}`} role="status"><i/>{t(`connection.${['online','offline','error'].includes(connection)?connection:'connecting'}` as 'connection.online')}</div><div className="language-switch" role="group" aria-label={t('app.language')}><button lang="ru" aria-pressed={locale==='ru-RU'} onClick={()=>setLocale('ru-RU')}>Русский</button><button lang="tt" aria-pressed={locale==='tt-RU'} onClick={()=>setLocale('tt-RU')}>Татарча</button></div><button className="presentation-toggle" aria-pressed={presentation} onClick={()=>setPresentation(v=>!v)}>{presentation?'↙':'↗'} {t(presentation?'app.exit':'app.presentation')}</button></div></header>
 <section className="intro"><div><span className="eyebrow">{t('app.eyebrow')}</span><h1>{t('app.title')}</h1><p>{t('app.description')}</p></div><div className="session-id"><span>{t('app.live')}</span><strong>{t('app.session',{scenario:t(`scenario.${data?.session.scenario||session.scenario}` as 'scenario.easy'),seed:n(data?.session.seed??session.seed,0)})}</strong><small>ROS 2 Jazzy · Gazebo Harmonic</small></div></section>
 <section className="metrics" aria-label={t('mission.state')}><div><label>{t('metric.energy')}</label><strong>{obs?n(obs.battery):'—'}<small> / 60</small></strong><div className={`battery ${(obs?.battery??60)<8?'low':''}`}><i style={{width:`${Math.max(0,Math.min(100,(obs?.battery??0)/60*100))}%`}}/></div></div><div><label>{t('metric.collected')}</label><strong>{data?n(data.state.collected,0):'—'}<small> / {n(total,0)}</small></strong><span>{t('metric.confirmed')}</span></div><div><label>{t('metric.delivered')}</label><strong>{data?n(data.state.delivered,0):'—'}<small> / {n(total,0)}</small></strong><span>{t('map.base')}</span></div><div><label>{t('mission.state')}</label><strong className={`status ${status}`}>{statusText(status,t)}</strong><span>{t('mission.time',{time:obs?n(obs.sim_time):'—'})}</span></div><div><label>{t('metric.source')}</label><strong className="source-value">{source}</strong><span>{t('agent.sourceHint')}</span></div></section>
 <div className="workspace"><section className="panel map-panel" id="mission-map"><div className="panel-head"><h2><i className="section-dot"/>{t('map.title')}</h2><span>01 / TurtleBot3</span></div><WorldMap data={data} grid={grid} online={online} presentation={presentation} onInspect={setCost}/>{mapError&&<p className="map-error" role="alert">{t('map.unavailable')} <button disabled={!online} onClick={()=>setMapAttempt(v=>v+1)}>{t('map.retry')}</button></p>}<div className="objective"><span>{t('agent.objective')}</span><strong>{objective}</strong>{active&&data?.state.goal?.target&&<small>{t('map.position',{x:n(data.state.goal.target.x,2),y:n(data.state.goal.target.y,2)})}</small>}</div></section>
 <aside><section className="panel decision"><div className="panel-head"><h2>{t('agent.title')}</h2><span>02</span></div><div className="decision-body"><span className="eyebrow">{t('agent.objective')}</span><h3>{objective}</h3><div className="decision-source"><span>{t('metric.source')}</span><strong>{source}</strong></div><div className="explanation"><label>{t('agent.explanation')}</label><p>{status==='finished'?t('agent.complete',{delivered:n(data?.state.delivered??0,0),total:n(total,0)}):reason.text}</p>{reason.original&&status!=='finished'&&<small className="original-tag">{t('journal.original')}</small>}</div><dl><div><dt>{t('mission.planner')}</dt><dd>{t((data?.session.planner_mode||session.planner_mode)==='llm'?'planner.llm':'planner.algorithmic')}</dd></div><div><dt>{t('mission.strategy')}</dt><dd>{t((data?.session.mode||session.mode)==='adaptive'?'mode.adaptive':'mode.baseline')}</dd></div><div><dt>{t('agent.stage')}</dt><dd>{statusText(status,t)}</dd></div></dl><div className="signal"><span>{t('agent.signal')}</span><strong>{obs?n(obs.signal,3):'—'}</strong><div className="battery"><i style={{width:`${Math.max(0,Math.min(100,(obs?.signal??0)*100))}%`}}/></div></div>{!online&&<p className="stale-note">{t('agent.stale')}</p>}{(data?.error||status==='failed'||safetyEvent)&&<div className="safety" role="alert"><strong>{t('agent.safety')}</strong>{failure&&<><p>{failure}</p><small>{t('journal.original')}</small></>}{safetyEvent&&<p>{t(eventKeys[safetyEvent.type] as 'event.collision')} · {t('journal.time',{time:n(safetyEvent.sim_time)})}</p>}</div>}<p className="event-note">{lastEvent?t('event.latest',{event:eventKeys[lastEvent.type]?t(eventKeys[lastEvent.type] as 'event.collision'):lastEvent.type}):t('event.none')}</p></div></section>
 <section className="panel control"><div className="panel-head"><h2>{t('mission.title')}</h2><span>03</span></div><div className="control-body"><p className="configuration-summary">{t('app.session',{scenario:t(`scenario.${selected.scenario}` as 'scenario.easy'),seed:Number.isFinite(selected.seed)?n(selected.seed,0):'—'})}</p><details className="settings"><summary>{t('mission.settings')}</summary><label>{t('mission.scenario')}</label><div className="scenario-buttons">{['easy','medium','hard'].map(s=><button key={s} className={selected.scenario===s?'selected':''} aria-pressed={selected.scenario===s} disabled={active||busy} onClick={()=>setSession(v=>({...v,scenario:s}))}>{t(`scenario.${s}` as 'scenario.easy')}</button>)}</div><p className="hint">{t(`scenario.${selected.scenario}Hint` as 'scenario.easyHint')}</p><label htmlFor="seed">{t('mission.seed')}</label><input id="seed" type="number" min="0" max="2147483647" step="1" value={Number.isNaN(selected.seed)?'':selected.seed} disabled={active||busy} onChange={e=>setSession(v=>({...v,seed:e.target.value===''?NaN:Number(e.target.value)}))}/><label htmlFor="mode">{t('mission.strategy')}</label><select id="mode" value={selected.mode} disabled={active||busy} onChange={e=>setSession(v=>({...v,mode:e.target.value}))}><option value="baseline">{t('mode.baseline')}</option><option value="adaptive">{t('mode.adaptive')}</option></select><label htmlFor="planner">{t('mission.planner')}</label><select id="planner" value={selected.planner_mode} disabled={active||busy} onChange={e=>setSession(v=>({...v,planner_mode:e.target.value}))}><option value="algorithmic">{t('planner.algorithmic')}</option><option value="llm">{t('planner.llm')}</option></select><p className="hint">{t('planner.hint')}</p></details>
 <button className="primary" disabled={!online||active||busy} onClick={()=>action('start')}>▶ {t('mission.start')}</button><div className="button-row"><button disabled={!online||busy||!['running','returning'].includes(status)} onClick={()=>action('pause')}>Ⅱ {t('mission.pause')}</button><button disabled={!online||busy||status!=='paused'} onClick={()=>action('resume')}>▷ {t('mission.resume')}</button></div><button disabled={!online||busy||!active} onClick={()=>action('return')}>↩ {t('mission.return')}</button><button className="danger" disabled={!online||busy||!active} onClick={()=>action('stop')}>■ {t('mission.stop')}</button><button className="reset" disabled={busy} onClick={()=>action('reset')}>↻ {t('mission.reset')}</button><div className="notice" role={notice&&['api','network','response','seed'].includes(notice.kind)?'alert':'status'}>{noticeText}{notice?.original&&<details><summary>{t('journal.original')}</summary><p>{notice.original}</p></details>}</div></div></section></aside></div>
 <div className="research-row"><EnergyPanel data={data} selected={cost} onSelect={setCost}/><Journal entries={data?.journal||[]} presentation={presentation}/></div><footer><span>DID LAB / DID HACK 2026</span><span>{t('app.public')}</span></footer><dialog ref={resetDialog} className="reset-dialog" aria-labelledby="reset-title" aria-describedby="reset-description" onCancel={()=>setResetPending(false)}><h2 id="reset-title">{t('mission.confirmTitle')}</h2><p id="reset-description">{t('mission.confirmReset')}</p><div className="button-row"><button onClick={()=>setResetPending(false)}>{t('mission.cancel')}</button><button className="danger" onClick={()=>{setResetPending(false);action('reset',true)}}>{t('mission.reset')}</button></div></dialog></main>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><I18nProvider><App/></I18nProvider></React.StrictMode>);
