import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
type Point={x:number;y:number};
type Session={scenario:string;seed:number;mode:string;planner_mode:string};
type Entry={sim_time:number;stage:string;text:string;hypothesis_id:string};
type Telemetry={connection:string;session:Session;state:{status:string;collected:number;delivered:number;goal:{action:string;target:Point|null;reason:string}|null;observation:{battery:number;signal:number;sim_time:number}|null};robot_pose:Point|null;robot_yaw:number;trajectory:Point[];planned_path:Point[];knowledge:{cell:Point;energy_per_m:number;uncertainty:number|null}[];journal:Entry[];planner_source:string;collected_positions:Point[];events:{type:string;sim_time:number}[];map_revision:number;error:string|null};
type Grid={width:number;height:number;resolution:number;origin:Point;origin_yaw:number;data:number[];revision:number};
const INITIAL:Session={scenario:'easy',seed:1,mode:'baseline',planner_mode:'algorithmic'};
function WorldMap({data,grid,online}:{data:Telemetry|null;grid:Grid|null;online:boolean}){
 const ref=useRef<HTMLCanvasElement>(null), raster=useRef<HTMLCanvasElement|null>(null);
 const [view,setView]=useState({x:0,y:0,zoom:125}),[pointer,setPointer]=useState<Point|null>(null),[layers,setLayers]=useState({path:true,visited:true,costs:true});
 const measured=useRef<{pose:Point;yaw:number}|null>(null);
 const drag=useRef<{x:number;y:number;vx:number;vy:number}|null>(null);
 useEffect(()=>{if(!grid)return;const c=document.createElement('canvas');c.width=grid.width;c.height=grid.height;const ctx=c.getContext('2d')!;const img=ctx.createImageData(c.width,c.height);grid.data.forEach((v,i)=>{const j=((grid.height-1-Math.floor(i/grid.width))*grid.width+i%grid.width)*4;const rgb=v<0?[26,32,44]:v>=50?[133,151,169]:[43,55,71];img.data.set([...rgb,255],j)});ctx.putImageData(img,0,0);raster.current=c},[grid]);
 useEffect(()=>{const c=ref.current;if(!c)return;const previous=measured.current;const began=performance.now();if(data?.robot_pose)measured.current={pose:data.robot_pose,yaw:data.robot_yaw};let raf=0;const draw=()=>{const rect=c.getBoundingClientRect();const dpr=devicePixelRatio||1;c.width=rect.width*dpr;c.height=rect.height*dpr;const ctx=c.getContext('2d')!;ctx.scale(dpr,dpr);const w=rect.width,h=rect.height,z=view.zoom;const px=(p:Point)=>({x:w/2+(p.x-view.x)*z,y:h/2-(p.y-view.y)*z});ctx.fillStyle='#0b111c';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#202c3d';ctx.lineWidth=.6;for(let x=Math.floor(view.x-w/2/z);x<view.x+w/2/z;x++){const u=px({x,y:0}).x;ctx.beginPath();ctx.moveTo(u,0);ctx.lineTo(u,h);ctx.stroke()}for(let y=Math.floor(view.y-h/2/z);y<view.y+h/2/z;y++){const v=px({x:0,y}).y;ctx.beginPath();ctx.moveTo(0,v);ctx.lineTo(w,v);ctx.stroke()}
 if(grid&&raster.current){const o=px(grid.origin);ctx.save();ctx.translate(o.x,o.y);ctx.rotate(-grid.origin_yaw);ctx.globalAlpha=.8;ctx.imageSmoothingEnabled=false;ctx.drawImage(raster.current,0,-grid.height*grid.resolution*z,grid.width*grid.resolution*z,grid.height*grid.resolution*z);ctx.restore()}
 if(layers.costs)data?.knowledge.forEach(e=>{const p=px(e.cell);ctx.fillStyle=`rgba(245,158,66,${Math.min(.65,(e.energy_per_m-1)*.12+.12)})`;ctx.fillRect(p.x-.25*z,p.y-.25*z,.5*z,.5*z);ctx.fillStyle='#ffd294';ctx.font='10px monospace';ctx.fillText(e.energy_per_m.toFixed(1),p.x-8,p.y+3)});
 const line=(points:Point[],color:string,dash:number[],width:number)=>{if(!points.length)return;ctx.beginPath();points.forEach((p,i)=>{const a=px(p);if(i)ctx.lineTo(a.x,a.y);else ctx.moveTo(a.x,a.y)});ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([])};
 if(layers.visited){ctx.fillStyle="rgba(77,184,156,.075)";(data?.trajectory||[]).forEach(q=>{const a=px(q);ctx.fillRect(a.x-.1*z,a.y-.1*z,.2*z,.2*z)})}if(layers.visited)line(data?.trajectory||[],'#57bba1',[],2);if(layers.path)line(data?.planned_path||[],'#8b99f2',[5,5],1.5);
 const home=px({x:-2,y:-.5});ctx.strokeStyle='#6bbaa6';ctx.strokeRect(home.x-8,home.y-8,16,16);ctx.font='10px monospace';ctx.fillStyle='#90b4b6';ctx.fillText('BASE',home.x+14,home.y+4);
 data?.collected_positions.forEach(p=>{const a=px(p);ctx.fillStyle='#eab85b';ctx.beginPath();ctx.arc(a.x,a.y,5,0,Math.PI*2);ctx.fill()});
 const goal=data?.state.goal?.target;if(goal){const a=px(goal);ctx.strokeStyle='#a9b0ff';ctx.beginPath();ctx.arc(a.x,a.y,8,0,Math.PI*2);ctx.moveTo(a.x-12,a.y);ctx.lineTo(a.x+12,a.y);ctx.moveTo(a.x,a.y-12);ctx.lineTo(a.x,a.y+12);ctx.stroke()}
 if(data?.robot_pose){const f=online?Math.min(1,(performance.now()-began)/200):1;const actual=data.robot_pose;const source=previous?.pose||actual;const displayed={x:source.x+(actual.x-source.x)*f,y:source.y+(actual.y-source.y)*f};const oldYaw=previous?.yaw??data.robot_yaw;const delta=Math.atan2(Math.sin(data.robot_yaw-oldYaw),Math.cos(data.robot_yaw-oldYaw));const p=px(displayed);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(-(oldYaw+delta*f));ctx.shadowBlur=online?18:0;ctx.shadowColor='#64e1cf';ctx.fillStyle=online?'#65e1ca':'#778699';ctx.beginPath();ctx.moveTo(13,0);ctx.lineTo(-8,-8);ctx.lineTo(-4,0);ctx.lineTo(-8,8);ctx.closePath();ctx.fill();ctx.restore();ctx.font='11px monospace';ctx.fillStyle='#adc4d5';ctx.fillText(`(${data.robot_pose.x.toFixed(2)}, ${data.robot_pose.y.toFixed(2)})`,p.x+19,p.y-13)}
 ctx.fillStyle='#879bb2';ctx.font='10px monospace';ctx.fillText('MAP FRAME · meters',16,h-17);ctx.fillRect(w-99,h-23,z*.5,2);ctx.fillText('0.5 m',w-99,h-30);if(online&&performance.now()-began<200)raf=requestAnimationFrame(draw);
 };draw();const observer=new ResizeObserver(draw);observer.observe(c);return()=>{observer.disconnect();cancelAnimationFrame(raf)}},[data,grid,view,layers,online]);
 return <div className="map-area"><canvas ref={ref} aria-label="Live ROS occupancy map" onWheel={e=>{e.preventDefault();setView(v=>({...v,zoom:Math.max(30,Math.min(240,v.zoom*(e.deltaY>0?.9:1.1)))}))}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y}}} onPointerUp={()=>{drag.current=null}} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setPointer({x:view.x+(e.clientX-r.left-r.width/2)/view.zoom,y:view.y-(e.clientY-r.top-r.height/2)/view.zoom});if(drag.current){const d=drag.current;setView(v=>({...v,x:d.vx-(e.clientX-d.x)/v.zoom,y:d.vy+(e.clientY-d.y)/v.zoom}))}}}/>
 <div className="map-tools"><button title="Zoom in" onClick={()=>setView(v=>({...v,zoom:Math.min(240,v.zoom*1.2)}))}>+</button><button title="Zoom out" onClick={()=>setView(v=>({...v,zoom:Math.max(30,v.zoom/1.2)}))}>−</button><button onClick={()=>setView(v=>({...v,x:data?.robot_pose?.x??-2,y:data?.robot_pose?.y??-.5}))}>◎ Center robot</button></div>
 <div className="map-layers">{Object.entries(layers).map(([k,v])=><label key={k}><input type="checkbox" checked={v} onChange={()=>setLayers(l=>({...l,[k]:!v}))}/>{k==='costs'?'Inferred costs':k==='visited'?'Trajectory':'Planned path'}</label>)}</div>
 <div className="legend"><span className="dot mint"/>Robot / actual motion <span className="dot purple"/>Goal / route <span className="dot amber"/>Collected / measured cost</div>
 <div className="cursor">{pointer?`${pointer.x.toFixed(2)}, ${pointer.y.toFixed(2)} m`:'Drag to pan · scroll to zoom'}</div>
 {!online&&<div className="map-offline">{data?'STALE / DISCONNECTED — last observed position':'Waiting for ROS telemetry'}<small>No simulated movement</small></div>}
 </div>
}
function App(){
 const [data,setData]=useState<Telemetry|null>(null),[grid,setGrid]=useState<Grid|null>(null),[session,setSession]=useState(INITIAL),[socket,setSocket]=useState('connecting'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[tab,setTab]=useState('all');const received=useRef(0);
 useEffect(()=>{let ws:WebSocket,timer:ReturnType<typeof setTimeout>,alive=true;function connect(){if(!alive)return;setSocket('connecting');ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/telemetry`);ws.onopen=()=>setSocket('online');ws.onmessage=e=>{try{const v=JSON.parse(e.data) as Telemetry;received.current=Date.now();setData(v)}catch{setSocket('error')}};ws.onerror=()=>setSocket('error');ws.onclose=()=>{setSocket('offline');if(alive)timer=setTimeout(connect,2000)}}connect();const stale=setInterval(()=>{if(received.current&&Date.now()-received.current>2000)setSocket('offline')},500);return()=>{alive=false;clearTimeout(timer);clearInterval(stale);ws?.close()}},[]);
 useEffect(()=>{if(!data?.map_revision)return;fetch('/api/map').then(r=>{if(!r.ok)throw Error('Map unavailable');return r.json()}).then(setGrid).catch(()=>setGrid(null))},[data?.map_revision,data?.session.seed,data?.session.scenario]);
 const connection=socket==='online'?(data?.connection||'connecting'):socket,online=connection==='online',status=data?.state.status||'idle',active=['running','paused','returning'].includes(status),obs=data?.state.observation;
 async function action(cmd:string){setBusy(true);setMessage('');try{if(!Number.isInteger(session.seed)||session.seed<0||session.seed>2147483647)throw Error('Seed must be an integer from 0 to 2147483647');const r=await fetch(cmd==='start'?'/api/missions':cmd==='reset'?'/api/missions/reset':'/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cmd==='start'||cmd==='reset'?session:{command:cmd})});const body=await r.json();if(!r.ok)throw Error(typeof body.detail==='string'?body.detail:JSON.stringify(body.detail));if(cmd==='reset'){setGrid(null);setData(null)}setMessage(cmd==='reset'?'New simulator and judge session ready':`ROS accepted: ${cmd}`)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 const selected=active&&data?data.session:session;
 const total={easy:3,medium:5,hard:7}[data?.session.scenario||session.scenario]??3;
 const journal=(data?.journal||[]).filter(e=>tab==='all'||e.stage===tab).slice(-100).reverse();
 return <main><header><div className="brand"><div className="brandmark">D<span>↗</span></div><div><strong>DID LAB<span className="badge">RESEARCH CONSOLE</span></strong><p>Autonomous AI Researcher</p></div></div><div className={`connection ${connection}`}><span className="dot"/>{connection==='online'?'SIMULATION ONLINE':connection==='offline'?'SIMULATION OFFLINE':connection.toUpperCase()}<small>ROS 2 JAZZY · GAZEBO HARMONIC</small></div></header>
 <section className="intro"><div><span className="eyebrow">SINGLE AGENT / LIVE SIMULATION</span><h1>Explore. Observe. Adapt.</h1><p>An autonomous field researcher, learning from the world one observation at a time.</p></div><div className="session-id">MOCK JUDGE<span>{data?.session.scenario.toUpperCase()||'EASY'} · SEED {data?.session.seed??1}</span></div></section>
 <section className="metrics"><div><label>ENERGY REMAINING</label><strong>{obs?obs.battery.toFixed(1):'—'}<small> / 60</small></strong><div className="battery"><i style={{width:`${Math.max(0,Math.min(100,(obs?.battery??0)/60*100))}%`}}/></div></div><div><label>SAMPLES COLLECTED</label><strong>{data?.state.collected??0}<small> / {total}</small></strong><span>Confirmed by judge</span></div><div><label>DELIVERED TO BASE</label><strong>{data?.state.delivered??0}<small> samples</small></strong><span>Finish acknowledged</span></div><div><label>MISSION STATE</label><strong className={`status ${status}`}>{status.toUpperCase()}</strong><span>t = {obs?.sim_time.toFixed(1)??'—'} s · simulation time</span></div><div><label>PLANNER SOURCE</label><strong>{data?.planner_source||'Algorithmic'}</strong><span>{data?.session.mode==='adaptive'?'Measured energy adaptation':'Deterministic baseline'}</span></div></section>
 <section className="workspace"><div className="panel map-panel"><div className="panel-head"><h2><span className="dot mint"/>Environment</h2><span>OCCUPANCY MAP / LIVE ODOMETRY</span></div><WorldMap data={data} grid={grid} online={online}/><div className="objective"><span>CURRENT OBJECTIVE</span><strong>{status==='finished'?'Mission completed':status==='failed'?'Safety stop':status==='stopped'?'Mission stopped':data?.state.goal?.action.replaceAll('_',' ')||'Awaiting mission start'}</strong><small>{status==='finished'?`Delivered ${data?.state.delivered} of ${total} samples · finish confirmed`:status==='stopped'?'Motion stopped by command':status==='failed'?[...(data?.journal||[])].reverse().find(e=>e.text.startsWith('Failure:'))?.text||'See research journal':data?.state.goal?.reason||'Select a scenario and start an autonomous run.'}</small></div></div>
 <aside className="panel control"><div className="panel-head"><h2>Mission control</h2><span>01</span></div><label>SCENARIO</label><div className="scenario-buttons">{['easy','medium','hard'].map(s=><button key={s} className={selected.scenario===s?'selected':''} disabled={active||busy} onClick={()=>setSession(v=>({...v,scenario:s}))}>{s.toUpperCase()}</button>)}</div><p className="hint">{{easy:'3 samples · 1 static cost zone',medium:'5 samples · 3 static cost zones',hard:'7 samples · 4 zones · concealed changes'}[selected.scenario]}</p><label htmlFor="seed">RANDOM SEED</label><input id="seed" type="number" min="0" max="2147483647" step="1" value={Number.isNaN(selected.seed)?'':selected.seed} disabled={active||busy} onChange={e=>setSession(v=>({...v,seed:Number(e.target.value)}))}/><label htmlFor="mode">ENERGY STRATEGY</label><select id="mode" value={selected.mode} disabled={active||busy} onChange={e=>setSession(v=>({...v,mode:e.target.value}))}><option value="baseline">Baseline · conservative budget</option><option value="adaptive">Adaptive · measured local costs</option></select><label htmlFor="planner">PLANNER MODE</label><select id="planner" value={selected.planner_mode} disabled={active||busy} onChange={e=>setSession(v=>({...v,planner_mode:e.target.value}))}><option value="algorithmic">Algorithmic</option><option value="llm">LLM · team adapter / fallback</option></select><p className="hint">LLM requires Sonya’s server-side adapter. Without it the source stays Algorithmic.</p>
 <button className="primary" disabled={!online||active||busy} onClick={()=>action('start')}>▶ Start mission</button><div className="button-row"><button disabled={!online||busy||!['running','returning'].includes(status)} onClick={()=>action('pause')}>Ⅱ Pause</button><button disabled={!online||busy||status!=='paused'} onClick={()=>action('resume')}>▷ Resume</button></div><button disabled={!online||busy||!active} onClick={()=>action('return')}>↩ Return to base</button><button className="danger" disabled={!online||busy||!active} onClick={()=>action('stop')}>■ Stop mission</button><button className="reset" disabled={busy} onClick={()=>action('reset')}>↻ Reset simulator & judge</button><div className="notice" role="status">{busy?'Waiting for ROS / simulator…':message||data?.error||'Safety watchdog active. Commands use real ROS services.'}</div><div className="event-note">{data?.events?.length?`Latest event: ${data.events.at(-1)?.type.replaceAll("_"," ")}`:"No judge events yet"}</div><div className="signal"><span>LOCAL SAMPLE SIGNAL</span><strong>{obs?obs.signal.toFixed(3):'—'}</strong><div className="battery"><i style={{width:`${(obs?.signal??0)*100}%`}}/></div><small>No hidden sample positions exposed</small></div></aside></section>
 <section className="panel journal"><div className="panel-head"><h2>Research journal <span className="badge">OBSERVED EVIDENCE</span></h2><span>{data?.journal.length??0} ENTRIES</span></div><div className="tabs">{['all','hypothesis','experiment','observation','conclusion','model_update','replan'].map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t.replace('_',' ')}</button>)}</div><div className="journal-list">{journal.length?journal.map((e,i)=><article key={`${e.sim_time}-${i}`}><time>{e.sim_time.toFixed(1)}s</time><span className={`stage ${e.stage}`}>{e.stage.replace('_',' ')}</span><p>{e.text}</p></article>):<div className="empty">Journal entries appear when the agent makes actual observations.<small>Hypotheses and conclusions are generated from measured energy, not invented narratives.</small></div>}</div></section><footer><span>DID HACK 2026 / AUTONOMOUS RESEARCH</span><span>Private environment truth stays inside the judge.</span></footer></main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
